export const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  LOGIN: "LOGIN",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  SIGN_IN_START: "SIGN_IN_START",
};
